/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;


import DAO.ProductoDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ProductoDTO;

/**
 *
 * @author jerss
 */
public class Productos extends javax.swing.JInternalFrame {
    
    DefaultTableModel mod = new DefaultTableModel();
    ProductoDAO pd = new ProductoDAO();
    ProductoDTO pdt = new ProductoDTO();
    SimpleDateFormat fec = new SimpleDateFormat("dd/MM/yyyy");
    ArrayList<ProductoDTO> vp = new ArrayList<>();

    public Productos() {
        initComponents();
        definirColumnas();
        listar();
    }

    private void listar() {
        vp = pd.listar();
        for (int i = 0; i < vp.size(); i++) {
            Object[] data = {vp.get(i).getCodigo(), vp.get(i).getNom_pro(), vp.get(i).getPre_pro(), vp.get(i).getStock_pro(), vp.get(i).getDescrip_pro(), vp.get(i).getCategoria_pro()
            };
            mod.addRow(data);

        }
    }

    private void definirColumnas() {
        mod.addColumn("Codigo");
        mod.addColumn("Nombre");
        mod.addColumn("Precio");
        mod.addColumn("Stock");
        mod.addColumn("Descripcion");
        mod.addColumn("Categoria");

        tblDatos.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoPro = new javax.swing.JTextField();
        txtNombrePro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPrecioPro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStockPro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescriPro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnIngresarProducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnActualizarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        cbxCategoria = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("CRUD Productos");

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel4.setText("Stock");

        btnIngresarProducto.setText("Ingresar");
        btnIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProductoActionPerformed(evt);
            }
        });

        jLabel5.setText("Descripcion");

        btnActualizarProducto.setText("Actualizar");
        btnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductoActionPerformed(evt);
            }
        });

        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        jLabel9.setText("Categoria");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "bebidas", "abarrotes", "lacteos", "snacks", "limpieza" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtStockPro)
                                                .addGap(136, 136, 136))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPrecioPro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIngresarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnActualizarProducto, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescriPro, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresarProducto)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarProducto)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecioPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtStockPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDescriPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProductoActionPerformed
        SimpleDateFormat fec = new SimpleDateFormat("dd/MM/yyyy");
        ProductoDTO pdt = new ProductoDTO();
        pd = new ProductoDAO();
        pdt.setCodigo(txtCodigoPro.getText());
        pdt.setNom_pro(txtNombrePro.getText());
        pdt.setPre_pro(Double.parseDouble(txtPrecioPro.getText()));
        pdt.setStock_pro(Integer.parseInt(txtStockPro.getText()));
        pdt.setDescrip_pro(txtDescriPro.getText());
        
        pdt.setCategoria_pro(cbxCategoria.getSelectedItem().toString());
        
        pd.insertar(pdt);
        limpiarTabla();
        listar();
        limpiar();

    }//GEN-LAST:event_btnIngresarProductoActionPerformed

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed
        
        ProductoDTO pdt = new ProductoDTO();
        pd = new ProductoDAO();
        pdt.setCodigo(txtCodigoPro.getText());
        pdt.setNom_pro(txtNombrePro.getText());
        pdt.setPre_pro(Double.parseDouble(txtPrecioPro.getText()));
        pdt.setStock_pro(Integer.parseInt(txtStockPro.getText()));
        pdt.setDescrip_pro(txtDescriPro.getText());
        
        pdt.setCategoria_pro(cbxCategoria.getSelectedItem().toString());
      
        pd.actualizar(pdt);
        limpiarTabla();
        listar();
        limpiar();

    }//GEN-LAST:event_btnActualizarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        ProductoDTO pdt = new ProductoDTO();
        pd = new ProductoDAO();
        int fila = tblDatos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null,
                    "Seleccione un producto para eliminar");
            return;
        }

        String cod = tblDatos.getValueAt(fila, 0).toString();

        pd.eliminar(cod);

        limpiarTabla();
        listar();
        limpiar();
        JOptionPane.showMessageDialog(null,
                "Producto eliminado correctamente");

    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked

        int fila = tblDatos.getSelectedRow();

        pdt.setCodigo(tblDatos.getValueAt(fila, 0).toString());
        pdt.setNom_pro(tblDatos.getValueAt(fila, 1).toString());
        pdt.setPre_pro(Double.parseDouble(tblDatos.getValueAt(fila, 2).toString()));
        pdt.setStock_pro(Integer.parseInt(tblDatos.getValueAt(fila, 3).toString()));
        pdt.setDescrip_pro(tblDatos.getValueAt(fila, 4).toString());
        
        pdt.setCategoria_pro(tblDatos.getValueAt(fila, 5).toString());

      

        txtCodigoPro.setText(pdt.getCodigo());
        txtNombrePro.setText(pdt.getNom_pro());
        txtPrecioPro.setText("" + pdt.getPre_pro());
        txtStockPro.setText("" + pdt.getStock_pro());
        txtDescriPro.setText(pdt.getDescrip_pro());
        
        cbxCategoria.setSelectedItem(pdt.getCategoria_pro());
        

    }//GEN-LAST:event_tblDatosMouseClicked
    private void limpiar() {
        txtCodigoPro.setText("");
        txtNombrePro.setText("");
        txtPrecioPro.setText("");
        txtStockPro.setText("");
        txtDescriPro.setText("");
        
        cbxCategoria.setSelectedIndex(0);
        
        txtCodigoPro.requestFocus();
    }
    public void limpiarTabla() {
        for (int i = 0; i < mod.getRowCount(); i++) {
            mod.removeRow(i);
            i = i - 1;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnIngresarProducto;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtCodigoPro;
    private javax.swing.JTextField txtDescriPro;
    private javax.swing.JTextField txtNombrePro;
    private javax.swing.JTextField txtPrecioPro;
    private javax.swing.JTextField txtStockPro;
    // End of variables declaration//GEN-END:variables
}
